version: 0.0
os: linux

files:
  - source: /
    destination: /home/ubuntu/drcloud-deploy
permissions:
  - object: /home/ubuntu/drcloud-deploy
    owner: ubuntu
    group: ubuntu
    mode: 755

steps:
  - run: yarn install
  - run: nest build
  - run: pm2 start ./dist/main.js
