version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/drcloud-deploy
permissions:
  - object: /home/ubuntu/drcloud-deploy
    owner: ubuntu
    group: ubuntu
    mode: 644
    acls:
      - "d:u::rwx"
      - "d:g::rwx"
      - "d:o::rwx"
     type: 
      - directory
    
hooks:
  ApplicationStart:
    - location: /deploy.sh
      timeout: 60
      runas: ubuntu
