version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/drcloud-deploy
permissions:
  - object: /home/ubuntu/drcloud-deploy
    owner: wemakers.team@gmail.com
    group: ${{ secrets.AWS_GROUP }}
    mode: 644

    
hooks:
  ApplicationStart:
    - location: /deploy.sh
      timeout: 60
      runas: ubuntu
